// Multi-language Support Translation Dictionary
export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'hi' | 'ja';

export const LANGUAGES: { code: LanguageCode; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    academy: 'Academy',
    simulator: 'Stock Arena',
    coach: 'AI Coach',
    dailyMissions: 'Daily Missions',
    growTreeShop: 'GrowTree Customization Shop',
    waterTree: 'Water GrowTree',
    level: 'Level',
    gold: 'Gold',
    streak: 'Streak',
    portfolioValue: 'Portfolio Value',
    buyingPower: 'Buying Power',
    recentTransactions: 'Recent Transactions',
    ticker: 'Ticker',
    price: 'Price',
    change: 'Change',
    buy: 'Buy',
    sell: 'Sell',
    loading: 'Loading AI Analysis...',
    askCoach: 'Ask your AI Investing Coach...',
    welcomeTitle: 'Welcome to GrowFolio!',
    welcomeSub: 'Learn professional investing, plant financial trees, and master the stock market.',
    achievementBadge: 'Unlocked Achievement',
    luckyWheel: 'Lucky Wheel',
    rewardsChest: 'Reward Chests',
    openChest: 'Open Chest',
    friendLeaderboard: 'Friends & Rivals',
    certificateOfCompletion: 'Certificate of Completion',
    onboardingTitle: 'Start Your Journey',
    onboardingExperience: 'Select Investment Experience',
    onboardingGoal: 'Choose Your Primary Goal',
    getStarted: 'Get Started',
  },
  es: {
    dashboard: 'Panel',
    academy: 'Academia',
    simulator: 'Arena de Acciones',
    coach: 'Entrenador IA',
    dailyMissions: 'Misiones Diarias',
    growTreeShop: 'Tienda GrowTree',
    waterTree: 'Regar GrowTree',
    level: 'Nivel',
    gold: 'Oro',
    streak: 'Racha',
    portfolioValue: 'Valor de Cartera',
    buyingPower: 'Poder de Compra',
    recentTransactions: 'Transacciones Recientes',
    ticker: 'Símbolo',
    price: 'Precio',
    change: 'Cambio',
    buy: 'Comprar',
    sell: 'Vender',
    loading: 'Cargando Análisis IA...',
    askCoach: 'Pregúntale a tu entrenador IA...',
    welcomeTitle: '¡Bienvenido a GrowFolio!',
    welcomeSub: 'Aprende inversión profesional, siembra árboles financieros y domina la bolsa.',
    achievementBadge: 'Logro Desbloqueado',
    luckyWheel: 'Rueda de la Suerte',
    rewardsChest: 'Cofres de Recompensas',
    openChest: 'Abrir Cofre',
    friendLeaderboard: 'Amigos y Rivales',
    certificateOfCompletion: 'Certificado de Finalización',
    onboardingTitle: 'Comienza tu Viaje',
    onboardingExperience: 'Selecciona Experiencia de Inversión',
    onboardingGoal: 'Elige tu Objetivo Principal',
    getStarted: 'Comenzar',
  },
  fr: {
    dashboard: 'Tableau de bord',
    academy: 'Académie',
    simulator: 'Arène Boursière',
    coach: 'Coach IA',
    dailyMissions: 'Missions Quotidiennes',
    growTreeShop: 'Boutique GrowTree',
    waterTree: 'Arroser GrowTree',
    level: 'Niveau',
    gold: 'Or',
    streak: 'Série',
    portfolioValue: 'Valeur du Portefeuille',
    buyingPower: 'Pouvoir d\'achat',
    recentTransactions: 'Transactions Récentes',
    ticker: 'Symbole',
    price: 'Prix',
    change: 'Variation',
    buy: 'Acheter',
    sell: 'Vendre',
    loading: 'Chargement de l\'analyse IA...',
    askCoach: 'Demandez à votre coach IA...',
    welcomeTitle: 'Bienvenue sur GrowFolio !',
    welcomeSub: 'Apprenez l\'investissement, cultivez des arbres financiers et maîtrisez le marché.',
    achievementBadge: 'Succès Déverrouillé',
    luckyWheel: 'Roue de la Fortune',
    rewardsChest: 'Coffres de Récompenses',
    openChest: 'Ouvrir le Coffre',
    friendLeaderboard: 'Amis & Rivaux',
    certificateOfCompletion: 'Certificat de Réussite',
    onboardingTitle: 'Commencez Votre Voyage',
    onboardingExperience: 'Sélectionnez Votre Expérience',
    onboardingGoal: 'Choisissez Votre Objectif Principal',
    getStarted: 'Commencer',
  },
  de: {
    dashboard: 'Dashboard',
    academy: 'Akademie',
    simulator: 'Aktien Arena',
    coach: 'KI-Coach',
    dailyMissions: 'Tägliche Missionen',
    growTreeShop: 'GrowTree-Shop',
    waterTree: 'GrowTree gießen',
    level: 'Level',
    gold: 'Gold',
    streak: 'Serie',
    portfolioValue: 'Portfolio-Wert',
    buyingPower: 'Kaufkraft',
    recentTransactions: 'Letzte Transaktionen',
    ticker: 'Kürzel',
    price: 'Preis',
    change: 'Änderung',
    buy: 'Kaufen',
    sell: 'Verkaufen',
    loading: 'Lade KI-Analyse...',
    askCoach: 'Fragen Sie Ihren KI-Investment-Coach...',
    welcomeTitle: 'Willkommen bei GrowFolio!',
    welcomeSub: 'Lernen Sie professionelles Investieren, pflanzen Sie Finanzbäume und meistern Sie die Börse.',
    achievementBadge: 'Erfolg freigeschaltet',
    luckyWheel: 'Glücksrad',
    rewardsChest: 'Belohnungstruhen',
    openChest: 'Truhe öffnen',
    friendLeaderboard: 'Freunde & Rivalen',
    certificateOfCompletion: 'Zertifikat über den Abschluss',
    onboardingTitle: 'Beginnen Sie Ihre Reise',
    onboardingExperience: 'Wählen Sie Ihre Anlageerfahrung',
    onboardingGoal: 'Wählen Sie Ihr Hauptziel',
    getStarted: 'Loslegen',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    academy: 'एकेडमी',
    simulator: 'स्टॉक एरिना',
    coach: 'एआई कोच',
    dailyMissions: 'दैनिक मिशन',
    growTreeShop: 'ग्रो-ट्री दुकान',
    waterTree: 'पौधे को पानी दें',
    level: 'स्तर',
    gold: 'सोना',
    streak: 'लगातार दिन',
    portfolioValue: 'पोर्टफोलियो मूल्य',
    buyingPower: 'क्रय शक्ति',
    recentTransactions: 'हाल के लेन-देन',
    ticker: 'टिकर',
    price: 'कीमत',
    change: 'बदलाव',
    buy: 'खरीदें',
    sell: 'बेचें',
    loading: 'एआई विश्लेषण लोड हो रहा है...',
    askCoach: 'अपने एआई इन्वेस्टिंग कोच से पूछें...',
    welcomeTitle: 'ग्रोफ़ोलियो में आपका स्वागत है!',
    welcomeSub: 'पेशेवर निवेश सीखें, वित्तीय पेड़ लगाएं और शेयर बाजार में महारत हासिल करें।',
    achievementBadge: 'उपलब्धि अनलॉक हुई',
    luckyWheel: 'भाग्य का पहिया',
    rewardsChest: 'पुरस्कार चेस्ट',
    openChest: 'चेस्ट खोलें',
    friendLeaderboard: 'मित्र और प्रतिद्वंद्वी',
    certificateOfCompletion: 'पूर्णता प्रमाण पत्र',
    onboardingTitle: 'अपनी यात्रा शुरू करें',
    onboardingExperience: 'निवेश का अनुभव चुनें',
    onboardingGoal: 'अपना प्राथमिक लक्ष्य चुनें',
    getStarted: 'शुरू करें',
  },
  ja: {
    dashboard: 'ダッシュボード',
    academy: 'アカデミー',
    simulator: '株式アリーナ',
    coach: 'AIコーチ',
    dailyMissions: 'デイリーミッション',
    growTreeShop: 'ツリーショップ',
    waterTree: 'ツリーに水やり',
    level: 'レベル',
    gold: 'ゴールド',
    streak: '連続日数',
    portfolioValue: '保有総資産',
    buyingPower: '余力資金',
    recentTransactions: '最近の取引履歴',
    ticker: 'ティッカー',
    price: '現在値',
    change: '前日比',
    buy: '買い',
    sell: '売り',
    loading: 'AI投資分析を生成中...',
    askCoach: 'AI投資コーチに質問する...',
    welcomeTitle: 'GrowFolioへようこそ！',
    welcomeSub: 'プロの投資手法を学び、金融の木を育て、株式市場を攻略しましょう。',
    achievementBadge: '実績を解除しました',
    luckyWheel: 'ラッキーホイール',
    rewardsChest: '報酬チェスト',
    openChest: '宝箱を開ける',
    friendLeaderboard: 'フレンド＆ライバル',
    certificateOfCompletion: '修了証明書',
    onboardingTitle: '投資の旅を始めましょう',
    onboardingExperience: '投資経験を選択してください',
    onboardingGoal: '主な目的を選択してください',
    getStarted: 'スタートする',
  },
};

export const getTranslation = (lang: LanguageCode, key: string): string => {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || key;
};
export default TRANSLATIONS;
